juntagrico_godparent/urls.py
from django.urls import path
from juntagrico_godparent import views

app_name = 'jgo'
urlpatterns = [
    # member urls
    path(app_name + '/home', views.home, name='home'),
    path(app_name + '/godparent', views.godparent_signup, name='godparent'),
    path(app_name + '/godparent/increment', views.increment_max_godchildren, name='increment-max-godchildren'),
    path(app_name + '/godchild', views.godchild_signup, name='godchild'),
    path(app_name + '/arranged/<int:godchild_id>', views.arranged, name='arranged'),
    path(app_name + '/done/<int:godchild_id>', views.done, name='done'),
    path(app_name + '/leave', views.leave, name='leave'),

    # admin urls
    path(app_name + '/manage/match', views.match, name='manage-match'),
    path(app_name + '/manage/matched', views.matched, name='manage-matched'),
    path(app_name + '/manage/matched/removed', views.matched, {'removed': True}, name='manage-matched-removed'),
    path(app_name + '/manage/unmatchable', views.unmatchable, name='manage-unmatchable'),
    path(app_name + '/manage/unmatch/<int:godchild_id>', views.unmatch, name='manage-unmatch'),
    path(app_name + '/manage/completed', views.completed, name='manage-completed'),
]

juntagrico_godparent/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext as _
from juntagrico.config import Config
from juntagrico.entity.member import Member
from juntagrico.util.temporal import weekday_choices, weekdays
from multiselectfield import MultiSelectField
from multiselectfield.db.fields import MSFList

from juntagrico_godparent.querysets import GodchildQuerySet, GodparentQuerySet
from juntagrico_godparent.util.utils import is_godparent, is_godchild, member_depot

LANGUAGES = (('de', 'Deutsch'),
             ('fr', 'Français'),
             ('it', 'Italiano'),
             ('ro', 'Rumantsch dal Grischun'),
             ('en', 'English'),
             ('pt', 'Português'),
             ('es', 'Español'),
             ('ot', _('Andere (Bitte unten angeben)')))


def week_slots_choices():
    return [
        (
            weekday, (
                (str(num) + 'am', _('Vormittag')),
                (str(num) + 'pm', _('Nachmittag')),
                (str(num) + 'ev', _('Abend')),
            )
        ) for num, weekday in weekday_choices
    ]


class Criteria(models.Model):
    member = models.OneToOneField(Member, verbose_name=Config.vocabulary('member'), on_delete=models.CASCADE)
    creation_date = models.DateField(_('Erstellungsdatum'), auto_now_add=True)
    languages = MultiSelectField(_('Verständigung'), choices=LANGUAGES, max_length=100,
                                 help_text=_('Wähle die Sprachen aus, die du sprichst.'))
    slots = MultiSelectField(_('Verfügbarkeit'), choices=week_slots_choices(), max_length=100,
                             help_text=_('Während diesen Zeitfenstern bin ich üblicherweise verfügbar und könnte mich '
                                         'zu einer Einführung bzw. einem ersten gemeinsamen Einsatz treffen.'))
    children = models.BooleanField(_(f'Ich habe Kinder, die ich zu den Einsätzen '
                                     f'bei {Config.organisation_name()} mitbringe'),
                                   help_text=_('Für Neumitglieder mit Kindern hat sich eine Einführung '
                                               'durch ein Gotte/Götti mit Kindern bewährt.'))
    comments = models.TextField(_('Bemerkungen und weitere Kriterien'), max_length=1000, default='', blank=True,
                                help_text=_('Was möchtest du uns noch mitteilen? Was sollten wir sonst '
                                            'noch beachten, bei der Vermittlung?'))

    @property
    def depot(self):
        return member_depot(self.member)

    def clean(self):
        if hasattr(self, 'member') and is_godparent(self.member) and is_godchild(self.member):
            raise ValidationError(_('Mitglied kann nicht Gotte/Götti und Neumtiglied gleichzeitig sein'))

    def admin_change_url_name(self):
        return "admin:juntagrico_godparent_" + self.__class__.__name__.lower() + "_change"

    def __str__(self):
        return str(self.member)

    class Meta:
        abstract = True


class Godparent(Criteria):
    max_godchildren = models.PositiveIntegerField(
        _('Anzahl Neumitglieder'), default=1,
        help_text=_('Wie viele Neumitglieder könntest du betreuen?')
    )

    objects = GodparentQuerySet.as_manager()

    def remaining_godchildren(self):
        return self.max_godchildren - self.godchild_set.matched().count()

    def save(self, *args, **kwargs):
        # keep max godchildren consistent
        if self.pk is not None:
            self.max_godchildren = max(self.godchild_set.matched().count(), self.max_godchildren)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('Gotte/Götti')
        verbose_name_plural = _('Gotte/Göttis')
        permissions = (('can_make_matches', _('Kann Gotte/Götti vermitteln')),)


class Godchild(Criteria):
    OPEN = 0
    ARRANGED = 1
    DONE = 2
    progress_choices = [
        (OPEN, _('Offen')),
        (ARRANGED, _('Abgemacht')),
        (DONE, _('Abgeschlossen')),
    ]

    talents = models.TextField(_('Interessen & Begabungen'), max_length=1000, default='', blank=True,
                               help_text=_('Hast du bestimmte Talente oder Fähigkeiten?'))
    godparent = models.ForeignKey(Godparent, verbose_name=_('Gotte/Götti'), on_delete=models.SET_NULL,
                                  null=True, blank=True)
    progress = models.IntegerField(default=0, choices=progress_choices)
    notes = models.TextField(
        _('Notizen'), max_length=1000, blank=True,
        help_text=_('Notizen für Administration. Nicht sichtbar für {}').format(Config.vocabulary('member')))

    objects = GodchildQuerySet.as_manager()

    def matching_languages(self):
        if self.godparent:
            return MSFList(self.languages.choices, set(self.languages).intersection(set(self.godparent.languages)))
        return set()

    def matching_slots(self):
        if self.godparent:
            # attach weekday to choice names
            choices = {k: weekdays[int(k[0])] + " " + v for k, v in self.slots.choices.items()}
            return MSFList(choices, set(self.slots).intersection(set(self.godparent.slots)))
        return set()

    def matching_areas(self):
        if self.godparent:
            return set(self.member.areas.all()).intersection(set(self.godparent.member.areas.all()))
        return set()

    def save(self, *args, **kwargs):
        # keep progress consistent
        if not self.godparent:
            self.progress = self.OPEN
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('Neumitglied')
        verbose_name_plural = _('Neumitglieder')

juntagrico_godparent/forms.py
from django.forms import ModelForm, Form, BooleanField, ModelMultipleChoiceField, CheckboxSelectMultiple, CharField
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from juntagrico.config import Config
from juntagrico.dao.activityareadao import ActivityAreaDao

from juntagrico_godparent.models import Godparent, Godchild
from juntagrico_godparent.util.customize import customizable


def contact_admin_link(text):
    return mark_safe(
        escape(
            text
        ).format('<a href="mailto:{0}">{0}</a>'.format(Config.info_email()))
    )


@customizable
class RegisterForm(Form):
    areas = ModelMultipleChoiceField(queryset=ActivityAreaDao.all_visible_areas_ordered(),
                                     widget=CheckboxSelectMultiple,
                                     label=_('Tätigkeitsbereiche'), required=False,
                                     help_text=_('Aktuell bist du in diesen Tätigkeitsbereichen eingetragen. '
                                                 'Bitte prüfe ob dies noch stimmt.<br>'
                                                 'Wenn du die Auswahl hier änderst, wirst du in die entsprechenden'
                                                 'Tätigkeitsbereiche eingetragen.'))
    email = CharField(label=_('E-Mail-Adresse'), disabled=True,
                      help_text=contact_admin_link(
                          _('Überprüfe deine E-Mail-Adresse. Kontaktiere {} um sie zu ändern.')))
    phone = CharField(label=_('Telefonnummer'), help_text='Überprüfe deine Telefonnummer')
    accept_terms = BooleanField(label=_('Ich bin einverstanden, dass meine E-Mail-Adresse und Telefonnummer '
                                        'dem vermittelten Mitglied mitgeteilt werden.'))

    def __init__(self, *args, editing=False, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', _('Ändern') if editing else _('Anmelden')))
        if editing:
            del self.fields['accept_terms']


@customizable
class GodparentForm(RegisterForm, ModelForm):
    class Meta:
        model = Godparent
        fields = ('max_godchildren', 'languages', 'slots', 'children', 'areas', 'comments')


@customizable
class GodchildForm(RegisterForm, ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['children'].help_text = _(f'Falls du Kinder hast, die du zu den '
                                              f'Einsätzen bei {Config.organisation_name()} mitbringen möchtest, '
                                              f'hat sich eine Einführung durch ein Mitglied bewährt, das selbst Kinder hat.')
        self.fields['children'].label = _('Gotte/Götti mit eigenen Kindern bevorzugen')

    class Meta:
        model = Godchild
        fields = ('languages', 'slots', 'children', 'talents', 'areas', 'comments')

juntagrico_godparent/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from juntagrico.util.views_admin import subscription_management_list
from juntagrico.view_decorators import highlighted_menu

from juntagrico_godparent.forms import GodparentForm, GodchildForm

from juntagrico_godparent.models import Godchild, Godparent
from juntagrico_godparent import signals
from juntagrico_godparent.templatetags.jgo.config import can_be_godparent
from juntagrico_godparent.util.matches import all_possible_matches, get_matched, all_unmatchable
from juntagrico_godparent.util.utils import is_godparent, is_godchild, was_godchild


@login_required
@highlighted_menu('jgo')
def home(request):
    member = request.user.member
    if is_godparent(member):
        return godparent_signup(request)
    if was_godchild(member) and not can_be_godparent(request.user):
        return godchild_done(request)
    if is_godchild(member):
        return godchild_signup(request)
    return render(request, "jgo/home.html")


def _registration(request, template, form_class, exists_function, instance_attr):
    member = request.user.member
    exists = exists_function(member)
    initial = dict(
        areas=member.areas.values_list('id', flat=True),
        email=member.email,
        phone=member.mobile_phone or member.phone
    )
    if request.method == 'POST' or exists:
        form = form_class(request.POST or None, instance=getattr(request.user.member, instance_attr) if exists else None,
                          editing=exists, initial=initial)
        if request.method == 'POST' and form.is_valid():
            member = request.user.member
            form.instance.member = member
            form.save()
            # send signal
            if not exists:
                signals.created.send(form.instance.__class__, instance=form.instance)
            else:
                signals.changed.send(form.instance.__class__, instance=form.instance)
            # update member
            if member.mobile_phone:
                member.mobile_phone = form.cleaned_data['phone']
            else:
                member.phone = form.cleaned_data['phone']
            member.save()
            member.areas.set(form.cleaned_data['areas'])
            return redirect('jgo:home')
    else:
        form = form_class(initial=initial)
    return render(request, f"jgo/{template}.html", dict(form=form, exists=exists))


@login_required
@highlighted_menu('jgo')
def godparent_signup(request):
    return _registration(request, 'godparent', GodparentForm, is_godparent, 'godparent')


@login_required
@highlighted_menu('jgo')
def godchild_signup(request):
    return _registration(request, 'godchild', GodchildForm, is_godchild, 'godchild')


@login_required
@highlighted_menu('jgo')
def godchild_done(request):
    return render(request, "jgo/godchild_done.html")


@login_required
def increment_max_godchildren(request):
    if is_godparent(request.user.member):
        gp = request.user.member.godparent
        gp.max_godchildren += 1
        gp.save()
        signals.reactivated.send(gp.__class__, instance=gp)
    return redirect('jgo:home')


@login_required
def leave(request):
    if is_godparent(request.user.member):
        request.user.member.godparent.delete()
    elif is_godchild(request.user.member):
        request.user.member.godchild.delete()
    return redirect('jgo:home')


@login_required
def arranged(request, godchild_id):
    godchild = get_object_or_404(Godchild, id=godchild_id)
    if godchild.progress == godchild.OPEN:
        member = request.user.member
        if member in [godchild.member, godchild.godparent.member]:
            godchild.progress = godchild.ARRANGED
            godchild.save()
            # TODO: Send email
    return redirect('jgo:home')


@login_required
def done(request, godchild_id):
    godchild = get_object_or_404(Godchild, id=godchild_id)
    if godchild.progress == godchild.ARRANGED:
        member = request.user.member
        if member in [godchild.member, godchild.godparent.member]:
            godchild.progress = godchild.DONE
            godchild.save()
            godchild.godparent.max_godchildren -= 1
            godchild.godparent.save()
            # TODO: Send email
    return redirect('jgo:home')


@permission_required('juntagrico_godparent.can_make_matches')
def match(request):
    render_dict = {
        'change_date_disabled': True,
        'available_godparents': Godparent.objects.available(),
        'remaining_godchildren': Godchild.objects.matched(False).count()
    }
    if request.method == 'POST':
        for name, value in request.POST.items():
            if name.startswith('match-') and value == 'on':
                godparent, godchild = name.split('-')[1:]
                godchild = get_object_or_404(Godchild, id=godchild)
                godchild.godparent_id = godparent
                godchild.save()
                signals.matched.send(godchild.__class__, godchild=godchild, matcher=request.user.member)
                render_dict['form_result'] = 'success'
    return subscription_management_list(all_possible_matches(), render_dict,
                                        'jgo/manage/match_maker.html', request)


@permission_required('juntagrico_godparent.can_make_matches')
def unmatchable(request):
    render_dict = {'change_date_disabled': True}
    if request.method == 'POST' and request.POST.get('godparent') and request.POST.get('godchild'):
        godchild = get_object_or_404(Godchild, id=request.POST.get('godchild'))
        godchild.godparent_id = request.POST.get('godparent')
        godchild.save()
        signals.matched.send(godchild.__class__, godchild=godchild, matcher=request.user.member)
        render_dict['form_result'] = 'success'
    return subscription_management_list(all_unmatchable(), render_dict,
                                        'jgo/manage/unmatchable.html', request)


@permission_required('juntagrico_godparent.can_make_matches')
def matched(request, removed=False):
    render_dict = {'change_date_disabled': True, 'removed': removed}
    return subscription_management_list(get_matched(), render_dict,
                                        'jgo/manage/matched.html', request)


@permission_required('juntagrico_godparent.can_make_matches')
def unmatch(request, godchild_id):
    godchild = get_object_or_404(Godchild, id=godchild_id)
    godchild.godparent = None
    godchild.save()
    return redirect('jgo:manage-matched-removed')


@permission_required('juntagrico_godparent.can_make_matches')
def completed(request):
    render_dict = {'change_date_disabled': True}
    return subscription_management_list(Godchild.objects.completed(), render_dict,
                                        'jgo/manage/completed.html', request)

juntagrico_godparent/templates/jgo/godchild_done.html
{% extends "base.html" %}
{% load jgo.config %}
{% load juntagrico.config %}
{% load i18n %}
{% load static %}

{% block page_title %}
    <h3>Patenschaft abgeschlossen</h3>
{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="col-md-12">
            {% config "organisation_name" as c_organization_name %}
            {% jgo_config "contact" as c_contact %}
            {% block godchild_done_info %}
                <h4>Danke, dass du am Patenschaftsprogramm teilgenommen hast</h4>
                <p>Wir hoffen du hattest dadurch einen besseren Start bei {{ c_organization_name }}.</p>
                <p>
                    Melde dich ungeniert bei der Patenschaftskoordination (<a href="mailto:{{ c_contact }}">{{ c_contact }}</a>),
                    falls du Anmerkungen oder Verbesserungsvorschläge hast.
                </p>
            {% endblock %}
        </div>
    </div>
{% endblock %}

juntagrico_godparent/templates/jgo/godparent.html
{% extends "base.html" %}
{% load juntagrico.config %}
{% load jgo.config %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_title %}
    {% if exists %}
        <h3>Dein Gotte/Götti-Profil</h3>
    {% else %}
        <h3>Melde dich als Gotte oder Götti an</h3>
    {% endif %}
{% endblock %}

{% block styles %}
    {{ block.super }}
    <link href="{% static 'jgo/css/registration.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
    {% if exists and not form.errors %}
        <div class="row mb-3">
            <div class="col-md-12 alert alert-success">
                {% block godchildren %}
                    {% for godchild in form.instance.godchild_set.matched %}
                        {% if forloop.first %}
                            <h4>{% trans "Von dir Betreut" %}</h4>
                            <em>
                            {% if forloop.revcounter > 1 %}
                                {% trans "Bitte melde dich innerhalb von zwei Wochen nach der Zuteilung durch die Patenschaftskoordination bei diesen Personen." %}
                            {% else %}
                                {% trans "Bitte melde dich innerhalb von zwei Wochen nach der Zuteilung durch die Patenschaftskoordination bei dieser Person." %}
                            {% endif %}
                            </em>
                        {% endif %}
                        <p>
                            <strong>{{ godchild }}</strong>:
                            <a href="mailto:{{ godchild.member.email }}">{{ godchild.member.email }}</a>,
                            {{ godchild.member.mobile_phone|default:godchild.member.phone }}<br>
                            {% trans "Gemeinsame Sprachen:" %} {{ godchild.matching_languages|default:'Keine' }}<br>
                            {% trans "Gemeinsame Zeitfenster:" %} {{ godchild.matching_slots|default:'Keine' }}<br>
                            {% trans "Gemeinsame Tätigkeitsbereiche:" %}
                            {% for area in godchild.matching_areas %}
                                {{ area.name }}{% if not forloop.last %},{% endif %}
                            {% empty %}
                                 {% trans "Keine" %}
                            {% endfor %}
                            <br>
                            {% trans "Status:" %} {{ godchild.get_progress_display }}<br>
                            {% if godchild.progress == godchild.OPEN %}
                                <a href="{% url "jgo:arranged" godchild.pk %}" class="btn btn-primary">
                                    {% blocktrans %}
                                        Ich habe den Kontakt mit {{ godchild }} aufgenommen
                                    {% endblocktrans %}
                                </a>
                            {% elif godchild.progress == godchild.ARRANGED %}
                                <a href="{% url "jgo:done" godchild.pk %}" class="btn btn-warning"
                                    onclick="return confirm('{% trans "Hiermit bestätigst du, dass du diese Patenschaft erfolgreich abgeschlossen hast." %}')">
                                    {% blocktrans %}
                                        Patenschaft mit {{ godchild }} abschliessen
                                    {% endblocktrans %}
                                </a>
                            {% endif %}
                            <br>
                        </p>
                    {% empty %}
                        {% if form.instance.remaining_godchildren > 0 %}
                            <h4>{% trans "Die Vermittlung läuft" %}</h4>
                            <p>{% trans "Danke für deine Anmeldung." %}</p>
                        {% elif form.instance.godchild_set.completed.exists %}
                            <h4>{% trans "Danke!" %}</h4>
                            <p>{% trans "Du hast alle deine Patenschaften abgeschlossen. Klicke hier, um Gotte/Götti für weitere Neumitglieder zu werden." %}</p>
                        {% else %}
                            <h4>{% trans "Fast geschaft!" %}</h4>
                            <p>{% trans "Du hast dein Gotte/Götti-Profil erstellt aber derzeit angegeben, dass du noch keine Neumitglieder betreuen kannst." %}</p>
                        {% endif %}
                    {% endfor %}
                {% endblock %}
                {% block remaining_godchildren %}
                    {% with form.instance.remaining_godchildren as rg %}
                        {% if rg <= 0 %}
                            <a href="{% url "jgo:increment-max-godchildren" %}" class="btn btn-primary">
                                {% trans "Ein weiteres Neumitglied betreuen" %}
                            </a>
                        {% else %}
                            {% if form.instance.godchild_set.matched.exists %}
                                <h4>{% trans "Die Vermittlung läuft weiter" %}</h4>
                            {% endif %}
                            {% if rg == 1 %}
                                {% trans "Die Patenschaftsvermittlung prüft derzeit, ob sie noch ein passendes Neumitglied für dich findet." %}
                            {% else %}
                                {% blocktrans %}
                                    Die Patenschaftsvermittlung prüft derzeit, ob sie noch {{ rg }} passende Neumitglieder für dich findet.
                                {% endblocktrans %}
                            {% endif %}
                            <br>
                            {% trans "Dies kann einige Tage in Anspruch nehmen. Du wirst per E-Mail informiert." %}
                            <br>
                            {% trans "Deine Kriterien kannst du unten anpassen." %}
                        {% endif %}
                    {% endwith %}
                {% endblock %}
            </div>
        </div>
    {% endif %}
    {% if not form.errors %}
        <div class="row mb-3">
            <div class="col-md-12">
                {% block godparent_info %}
                    {% jgo_config "contact" as c_contact %}
                    <h4>Informationen zur Patenschaft</h4>
                    <p>Als Gotte/Götti bist du eine Art Vertrauensperson für ein dir zugeteiltes Neumitglied.
                        Diesem erleichterst du den Start bei {% config "organisation_name" %}, indem du es in die Community
                        und den Solawi-Alltag einführst und ihm bei Fragen zur Verfügung stehst.</p>
                    <h5>Deine Aufgaben</h5>
                    <ul>
                        <li>Du nimmst innerhalb von zwei Wochen nach der Zuteilung mit dem neuen Mitglied Kontakt auf.</li>
                        <li>Zu Beginn der Saison leistet ihr gemeinsam einen Arbeitseinsatz.<br>
                            Bei diesem Einsatz zeigst du dem neuen Mitglied die Gärtnerei, machst es mit anderen Mitgliedern und Schlüsselpersonen vor Ort bekannt,
                            beantwortest allfällige Fragen und vermittelst, was solidarische Landwirtschaft (SoLaWi) und die Genossenschaft für dich bedeuten.<br>
                            Dafür orientierst du dich an der
                            <strong><a href="/t/patenschaft_checkliste" target="_blank">Checkliste</a></strong></li>
                        <li>Du stehst dem Neumitglied weiterhin als vertrauensvolle Ansprechperson zur Verfügung (es darf dich kontaktieren).</li>
                        <li>Bei Gelegenheit erkundest du seine Interessen und vernetzt es mit Mitgliedern mit
                            ähnlichen Interessen oder passenden Arbeits- und Projektgruppen.
                            Bei Bedarf kann dich die Patenschaftsbetreuung (<a href="mailto:{{ c_contact }}">{{ c_contact }}</a>) bei der Vernetzung unterstützen.</li>
                    </ul>
                    <h5>Das bringst du mit</h5>
                    <ul>
                        <li>Du bist mindestens ein Jahr Mitglied bei {% config "organisation_name" %}.</li>
                        <li>Du magst Menschen und gehst in einer interessierten und offene Haltung auf sie zu.</li>
                        <li>Dir liegt der Zusammenhalt der Community von {% config "organisation_name" %} und der Solawi-Gedanke am Herzen.</li>
                    </ul>
                    <h5>Darauf darfst du dich freuen</h5>
                    <ul>
                        <li>Du lernst über deine Projekt- und Arbeitsgruppe hinaus neue Mitglieder kennen, kommst
                            ins Gespräch über neue Themen und leistest einen wichtigen Beitrag zum
                            Zusammenhalt unserer Community.</li>
                        <li>Du erhältst ein Böhnli.</li>
                    </ul>
                {% endblock %}
            </div>
        </div>
    {% endif %}
    {% if form.instance.pk is None or form.instance.remaining_godchildren > 0 or form.errors %}
        <div class="row mb-3">
            <div class="col-md-12">
                <h4>
                    {% trans "Deine Kriterien" %}
                </h4>
                <p>
                    {% block godparent_form_info %}
                        {% blocktrans %}
                            Bitte fülle untenstehende Kriterien aus, damit dir ein möglichst passendes Neumitglied vermittelt werden kann.
                        {% endblocktrans %}
                    {% endblock %}
                </p>
            </div>
        </div>
        {% include "jgo/snippets/depot_info.html" %}
        {% crispy form %}
        {% if exists and not form.instance.godchild_set.count %}
            <div class="row mb-3">
                <div class="col-md-12">
                    <h4>
                        {% trans "Austragen" %}
                    </h4>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-12">
                    <p>
                        {% trans "Hiermit wird dein Gotte/Götti-Profil gelöscht. Du kannst es jederzeit neu erstellen" %}
                    </p>
                    <a href="{% url 'jgo:leave' %}" class="btn btn-danger">
                        {% trans "Ich will nicht mehr Gotte/Götti sein" %}
                    </a>
                </div>
            </div>
        {% endif %}
    {% endif %}
    {% if form.instance.pk and form.instance.godchild_set.completed.exists %}
        <div class="row mb-3">
            <div class="col-md-12">
                {% block godchildren_completed %}
                    <h4>{% trans "Vergangene Patenschaften" %}</h4>
                    <p>
                    Dank dir konnten folgende Neumitglieder erfolgreich bei {% config "organisation_name" %} starten.
                    </p>
                    <p>
                    {% for godchild in form.instance.godchild_set.completed %}
                        <strong>{{ godchild }}</strong>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </p>
                {% endblock %}
            </div>
        </div>
    {% endif %}
{% endblock %}

juntagrico_godparent/templates/jgo/matched.html
{% extends "jgo/man_list_matcher.html" %}
{% load i18n %}
{% load juntagrico.config %}
{% block page_title %}
    <h3>
        {% blocktrans %}Vermittelte Gotte & Göttis{% endblocktrans %}
    </h3>
{% endblock %}
{% block list %}
    {% if removed %}
        <div class="alert alert-success">
            {% trans "Neumitglied und Gotte/Götti wurden wieder getrennt." %}
        </div>
    {% endif %}
    <table id="filter-table" class="list table" style="display: table;">
        <thead>
            <tr>
                <th class="filter">
                    Gotte/Götti
                </th>
                <th>
                    Gleiches Depot
                </th>
                <th class="filter">
                    Neumitglied
                </th>
                <th class="filter">
                    Angemeldet am
                </th>
                <th class="d-none">
                    {% trans "E-Mail" %}
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for possible_match in management_list %}
                {% with godparent=possible_match.godparent godchild=possible_match.godchild %}
                    <tr class="godparent-{{ godparent.id }} godchild-{{ godchild.id }}">
                        <td>
                            {% include 'jgo/snippets/match_entry.html' with subject=godparent matching_slots=godchild.slots %}
                        </td>
                        <td>
                            {% if possible_match.same_depot %}
                                {% trans "Ja" %}
                            {% else %}
                                {% trans "Nein" %}
                            {% endif %}
                        </td>
                        <td>
                            {% include 'jgo/snippets/match_entry.html' with subject=godchild matching_slots=godparent.slots %}
                        </td>
                        <td>
                            {{ godchild.creation_date }}
                        </td>
                        <td class="email d-none">
                            {{ godparent.member.email }},{{ godchild.member.email }}
                        </td>
                        <td>
                            <a href="{% url 'jgo:unmatch' godchild.id %}" class="btn btn-danger">
                                {% trans "Trennen" %}
                            </a>
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}